### ISSUE TITLE
エラー発生時のログ運用の検討/実装

### ISSUE THREAD

**Issue by ghost** [hr-js/sta_access_manager#174]
5xx/4xx系エラーのログ出力をどうするか。

今の所こんな感じで考えている

- 5xx系エラー
    - エラー内容をslackに通知/ファイルに出力

- 4xx系エラー
    - ファイルに出力

fastifyのloggerでいける?ファイル出力はできそうだが...

**Comment by ghost** [comment]
fastifyのloggerはファイル出力だけにしておいて、slackは別に投げるのも可能

https://github.com/slackapi/node-slack-sdk

**Comment by krhrtky** [comment]
それで問題ないと思う。
あとは、↓の課題がクリアできれば問題ないはず。
## 課題
  - loggerのファイル出力

**Comment by ghost** [comment]
fastifyのloggerはpinoってやつらしいから多分いける気がする

https://github.com/pinojs/pino

```
pino.destination([target]) => SonicBoom
Create a Pino Destination instance: a stream-like object with significantly more throughput (over 30%) than a standard Node.js stream.

const pino = require('pino')
const logger = pino(pino.destination('./my-file'))
const logger2 = pino(pino.destination())
```

**Comment by ghost** [comment]
こんな感じでいけるっぽい

```js
const pino = require('pino');
const logger = pino({ prettyPrint: true }, pino.destination('./my-file'));
logger.info(new Error('it\'s error message'));
```
log

```log
[1537600036200] [32mINFO[39m (13375 on kozakatsumanoMacBook-puro.local): [36mit's error message[39m
    Error: it's error message
        at Object.<anonymous> (/Users/kojak/workspace/pino-example/index.js:3:13)
        at Module._compile (internal/modules/cjs/loader.js:654:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
        at Module.load (internal/modules/cjs/loader.js:566:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
        at Function.Module._load (internal/modules/cjs/loader.js:498:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
        at startup (internal/bootstrap/node.js:201:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

```

**Comment by krhrtky** [comment]
なら問題はないね
